ais:
  cable:
    Ra:
      origin: soma
    cm:
      origin: soma
  ions:
    ek:
      origin: soma
  kap:
    gkabar:
      value: 0.06802739150611964
  kdr:
    gkdrbar:
      origin: soma
  km3:
    gkmbar:
      value: 0.004901184505886043
  nax:
    gbar:
      value: 0.10270480922854122
    sh:
      origin: hillock
    sha:
      value: -4.443379902782963
  pas:
    e:
      origin: soma
    g:
      origin: soma
apical:
  cable:
    Ra:
      origin: soma
    cm:
      origin: soma
  ions:
    ek:
      origin: soma
  kad:
    gkabar:
    - max_loc: 300.0
      min_loc: 75.0
      origin: soma
      outside: 0.0
      slope: 0.00036416245298589046
      value: 0.06661530114257613
    - min_loc: 300.0
      origin: soma
      value: 0.1485518530644015
  kap:
    gkabar:
      max_loc: 75.0
      origin: soma
      outside: 0.0
      slope: 0.00036416245298589046
  kdr:
    gkdrbar:
      origin: soma
  nas:
    gbar:
    - value: 0.023417098948243772
    - custom:
        func: custom_filter_modify_slope_if_terminal
      min: 0.006469766665974186
      origin: parent
      slope: 0.
    sh:
      origin: soma
    sha:
      value: 0.0
  pas:
    e:
      origin: soma
    g:
      origin: soma
      slope: 5.30099625114372e-06
      tau: 78.49424487035584
axon:
  cable:
    Ra:
      origin: soma
    cm:
      origin: soma
  ions:
    ek:
      origin: soma
  kap:
    gkabar:
      origin: ais
  kdr:
    gkdrbar:
      origin: ais
  km3:
    gkmbar:
      origin: ais
  nax:
    gbar:
      value: 0.04975326238669657
    sh:
      origin: hillock
  pas:
    e:
      origin: soma
    g:
      origin: soma
hillock:
  cable:
    Ra:
      origin: soma
    cm:
      origin: soma
  ions:
    ek:
      origin: soma
  kap:
    gkabar:
      origin: soma
  kdr:
    gkdrbar:
      origin: soma
  km3:
    gkmbar:
      origin: soma
  nax:
    gbar:
      value: 0.042434828569331486
    sh:
      value: 4.832291379461294
  pas:
    e:
      origin: soma
    g:
      origin: soma
soma:
  Ca:
    gcamult:
      value: 0.9938218203657428
  Cacum:
    tau:
      value: 50.
  CadepK:
    gcakmult:
      value: 1.1546501972793597
  cable:
    Ra:
      value: 150.0
    cm:
      value: 1.0
  ions:
    ek:
      value: -90.0
  kap:
    gkabar:
      value: 0.03930311716863435
  kdr:
    gkdrbar:
      value: 0.010215721026483958
  km3:
    gkmbar:
      value: 0.004186785436852004
  nas:
    gbar:
      value: 0.042434828569331486
    sh:
      value: 4.832291379461294
  pas:
    e:
      value: -77.0
    g:
      value: 1.3739321158444962e-08
spine_head:
  cable:
    Ra:
      origin: soma
    cm:
      origin: soma
  pas:
    e:
      origin: soma
    g:
      origin: soma
spine_neck:
  cable:
    Ra:
      origin: soma
    cm:
      origin: soma
  pas:
    e:
      origin: soma
    g:
      origin: soma
